#!/usr/bin/env python3

import os

from app import app
import config as cfg


if __name__ == '__main__':
    os.chdir(os.path.dirname(__file__))
    
    app.run(host=cfg.host, port=cfg.port,
            debug=cfg.app_debug,
            reloarer=cfg.app_debug)